name: Installs dependencies, run tests, and deploys to firebase
'on':
  push:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
          cache: 'npm'
      - name: Install dependencies
        run: yarn ci
        working-directory: client
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
          cache: 'npm'
      - name: Install dependencies
        run: yarn ci
        working-directory: client
      - name: Run jest tests
        run: yarn test --coverage --runInBand
        working-directory: client
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
          cache: 'npm'
      - name: Install dependencies
        run: yarn ci
        working-directory: client
      - name: Build project
        run: yarn build
        working-directory: client
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        working-directory: client
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_REAL_ESTATE_APP_F45E1 }}'
          channelId: live
          projectId: real-estate-app-f45e1
